//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLogs
    {
        public int ActivityLogId { get; set; }
        public int UserId { get; set; }
        public int TableId { get; set; }
        public int OperationId { get; set; }
        public System.DateTime Date { get; set; }
        public string PrimaryKeyAffected { get; set; }
        public string FieldsAffected { get; set; }
    }
}
