//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public Addresses()
        {
            this.ClientAddresses = new HashSet<ClientAddresses>();
        }
    
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public bool Active { get; set; }
        public byte CountryId { get; set; }
        public int AddressId { get; set; }
        public string Suburb { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Location { get; set; }
        public string Longitud { get; set; }
        public string Latitud { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual States States { get; set; }
        public virtual ICollection<ClientAddresses> ClientAddresses { get; set; }
    }
}
