//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adverts
    {
        public Adverts()
        {
            this.ClientAdverts = new HashSet<ClientAdverts>();
        }
    
        public int AdvertId { get; set; }
        public string AdvertName { get; set; }
        public string AdvertDescription { get; set; }
        public string AdvertFile { get; set; }
        public string BaseURL { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ClientAdverts> ClientAdverts { get; set; }
    }
}
