//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alphabet
    {
        public Alphabet()
        {
            this.Products = new HashSet<Products>();
            this.Clients = new HashSet<Clients>();
            this.Brands = new HashSet<Brands>();
            this.InternationalProducts = new HashSet<InternationalProducts>();
        }
    
        public byte AlphabetId { get; set; }
        public string Letter { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual ICollection<Brands> Brands { get; set; }
        public virtual ICollection<InternationalProducts> InternationalProducts { get; set; }
    }
}
