//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public Applications()
        {
            this.ActivitySessions = new HashSet<ActivitySessions>();
            this.Tables = new HashSet<Tables>();
            this.ApplicationUsers = new HashSet<ApplicationUsers>();
        }
    
        public int ApplicationId { get; set; }
        public string Description { get; set; }
        public string HashKey { get; set; }
        public string URL { get; set; }
        public string RootUrl { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string DocumentFile { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ActivitySessions> ActivitySessions { get; set; }
        public virtual ICollection<Tables> Tables { get; set; }
        public virtual ICollection<ApplicationUsers> ApplicationUsers { get; set; }
    }
}
