//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarCodes
    {
        public BarCodes()
        {
            this.ClientProductBarCodes = new HashSet<ClientProductBarCodes>();
        }
    
        public int BarCodeId { get; set; }
        public string BarCode { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ClientProductBarCodes> ClientProductBarCodes { get; set; }
    }
}
