//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Editions = new HashSet<Editions>();
        }
    
        public int BookId { get; set; }
        public string BookName { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Editions> Editions { get; set; }
    }
}
