//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brands
    {
        public Brands()
        {
            this.ClientBrands = new HashSet<ClientBrands>();
        }
    
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string Logo { get; set; }
        public bool Active { get; set; }
        public string BaseURL { get; set; }
        public Nullable<byte> AlphabetId { get; set; }
    
        public virtual Alphabet Alphabet { get; set; }
        public virtual ICollection<ClientBrands> ClientBrands { get; set; }
    }
}
