//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProductBarCodes
    {
        public int ClientId { get; set; }
        public int ProductId { get; set; }
        public int BarCodeId { get; set; }
        public Nullable<double> AveragePrice { get; set; }
    
        public virtual BarCodes BarCodes { get; set; }
        public virtual ClientProducts ClientProducts { get; set; }
    }
}
