//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientBrands
    {
        public Nullable<byte> ClientBrandTypeId { get; set; }
        public string Page { get; set; }
        public string ExpireDescription { get; set; }
        public int EditionId { get; set; }
        public int ClientId { get; set; }
        public int BrandId { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual EditionClients EditionClients { get; set; }
        public virtual ClientBrandTypes ClientBrandTypes { get; set; }
    }
}
