//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProductAdverts
    {
        public ClientProductAdverts()
        {
            this.EditionClientProductAdverts = new HashSet<EditionClientProductAdverts>();
        }
    
        public int ClientId { get; set; }
        public int ProductAdvertId { get; set; }
    
        public virtual ProductAdverts ProductAdverts { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual ICollection<EditionClientProductAdverts> EditionClientProductAdverts { get; set; }
    }
}
