//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientTypes
    {
        public ClientTypes()
        {
            this.EditionClients = new HashSet<EditionClients>();
        }
    
        public byte ClientTypeId { get; set; }
        public string TypeName { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<EditionClients> EditionClients { get; set; }
    }
}
