//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAdvertCategories
    {
        public int ClientId { get; set; }
        public int AdvertId { get; set; }
        public int EditionId { get; set; }
        public int CategoryThreeId { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<byte> AdvertTypeId { get; set; }
    
        public virtual AdvertTypes AdvertTypes { get; set; }
        public virtual CategoriesThree CategoryThree { get; set; }
        public virtual ClientAdverts ClientAdverts { get; set; }
        public virtual EditionClients EditionClients { get; set; }
    }
}
