//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPhones
    {
        public int ClientPhoneId { get; set; }
        public byte PhoneTypeId { get; set; }
        public string Number { get; set; }
        public string Lada { get; set; }
        public bool Active { get; set; }
        public int ClientId { get; set; }
        public int AddressId { get; set; }
        public string LocationLada { get; set; }
    
        public virtual ClientAddresses ClientAddresses { get; set; }
        public virtual PhoneTypes PhoneTypes { get; set; }
    }
}
