//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAddresses
    {
        public ClientAddresses()
        {
            this.ClientPhones = new HashSet<ClientPhones>();
        }
    
        public int ClientId { get; set; }
        public int AddressId { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual ICollection<ClientPhones> ClientPhones { get; set; }
    }
}
