//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAdverts
    {
        public ClientAdverts()
        {
            this.ClientAdvertCategories = new HashSet<ClientAdvertCategories>();
        }
    
        public int ClientId { get; set; }
        public int AdvertId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Adverts Adverts { get; set; }
        public virtual ICollection<ClientAdvertCategories> ClientAdvertCategories { get; set; }
    }
}
