//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountriesUser
    {
        public CountriesUser()
        {
            this.Users = new HashSet<Users>();
            this.UserCountries = new HashSet<UserCountries>();
        }
    
        public int CountryId { get; set; }
        public int RegionId { get; set; }
        public string CountryName { get; set; }
        public string ID { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<UserCountries> UserCountries { get; set; }
    }
}
