//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorProducts
    {
        public int DistributorId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Distributors Distributors { get; set; }
        public virtual Products Products { get; set; }
    }
}
