//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditionCategoryThree
    {
        public int EditionId { get; set; }
        public int CategoryThreeId { get; set; }
        public string CategoryProductPage { get; set; }
        public string CategoryPSPage { get; set; }
    
        public virtual CategoriesThree CategoryThree { get; set; }
        public virtual Editions Editions { get; set; }
    }
}
