//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditionClientProductShots
    {
        public EditionClientProductShots()
        {
            this.EditionProductShotSizes = new HashSet<EditionProductShotSizes>();
        }
    
        public int EditionClientProductShotId { get; set; }
        public bool Active { get; set; }
        public string ProductShot { get; set; }
        public Nullable<int> EditionId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual ParticipantProducts ParticipantProducts { get; set; }
        public virtual ICollection<EditionProductShotSizes> EditionProductShotSizes { get; set; }
    }
}
