//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditionClients
    {
        public EditionClients()
        {
            this.ClientBrands = new HashSet<ClientBrands>();
            this.InternationalEditionClientProducts = new HashSet<InternationalEditionClientProducts>();
            this.EditionClientProductAdverts = new HashSet<EditionClientProductAdverts>();
            this.ClientAdvertCategories = new HashSet<ClientAdvertCategories>();
        }
    
        public int EditionId { get; set; }
        public int ClientId { get; set; }
        public string Page { get; set; }
        public byte ClientTypeId { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ClientTypes ClientTypes { get; set; }
        public virtual Editions Editions { get; set; }
        public virtual ICollection<ClientBrands> ClientBrands { get; set; }
        public virtual ICollection<InternationalEditionClientProducts> InternationalEditionClientProducts { get; set; }
        public virtual ICollection<EditionClientProductAdverts> EditionClientProductAdverts { get; set; }
        public virtual ICollection<ClientAdvertCategories> ClientAdvertCategories { get; set; }
    }
}
