//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditionAttributeGroup
    {
        public int AttributeGroupId { get; set; }
        public int AttributeId { get; set; }
        public int EditionId { get; set; }
    
        public virtual EditionAttributes EditionAttributes { get; set; }
        public virtual AttributeGroup AttributeGroup { get; set; }
    }
}
