//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditionProductShotSizes
    {
        public int EditionClientProductShotId { get; set; }
        public byte ImageSizeId { get; set; }
    
        public virtual EditionClientProductShots EditionClientProductShots { get; set; }
        public virtual ImageSizes ImageSizes { get; set; }
    }
}
