//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageSizes
    {
        public ImageSizes()
        {
            this.EditionProductShotSizes = new HashSet<EditionProductShotSizes>();
        }
    
        public byte ImageSizeId { get; set; }
        public string ImageSize { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<EditionProductShotSizes> EditionProductShotSizes { get; set; }
    }
}
