//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternationalProducts
    {
        public InternationalProducts()
        {
            this.InternationalClientProducts = new HashSet<InternationalClientProducts>();
        }
    
        public int InternationalProductId { get; set; }
        public string InternationalProductName { get; set; }
        public bool Active { get; set; }
        public Nullable<byte> AlphabetId { get; set; }
    
        public virtual Alphabet Alphabet { get; set; }
        public virtual ICollection<InternationalClientProducts> InternationalClientProducts { get; set; }
    }
}
