//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternationalClientProducts
    {
        public InternationalClientProducts()
        {
            this.InternationalEditionClientProducts = new HashSet<InternationalEditionClientProducts>();
        }
    
        public int InternationalProductId { get; set; }
        public int ClientId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual InternationalProducts InternationalProducts { get; set; }
        public virtual ICollection<InternationalEditionClientProducts> InternationalEditionClientProducts { get; set; }
    }
}
