//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternationalEditionClientProducts
    {
        public int EditionId { get; set; }
        public int ClientId { get; set; }
        public int InternationalProductId { get; set; }
    
        public virtual EditionClients EditionClients { get; set; }
        public virtual InternationalClientProducts InternationalClientProducts { get; set; }
    }
}
