//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeafCategories
    {
        public LeafCategories()
        {
            this.LeafHomogeneousCategories = new HashSet<LeafHomogeneousCategories>();
        }
    
        public int LeafCategoryId { get; set; }
        public string LeafCategory { get; set; }
        public byte Level { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<LeafHomogeneousCategories> LeafHomogeneousCategories { get; set; }
    }
}
