//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeafHomogeneousCategories
    {
        public LeafHomogeneousCategories()
        {
            this.ClientProductLeafCategories = new HashSet<ClientProductLeafCategories>();
            this.ReassignCategories = new HashSet<ReassignCategories>();
        }
    
        public int LeafCategoryId { get; set; }
        public int CategoryThreeId { get; set; }
    
        public virtual ICollection<ClientProductLeafCategories> ClientProductLeafCategories { get; set; }
        public virtual ICollection<ReassignCategories> ReassignCategories { get; set; }
        public virtual LeafCategories LeafCategories { get; set; }
        public virtual CategoriesThree CategoriesThree { get; set; }
    }
}
