//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturers
    {
        public Manufacturers()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int ManufacturerId { get; set; }
        public string Manufacturer { get; set; }
        public bool Active { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
