//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantProducts
    {
        public ParticipantProducts()
        {
            this.EditionClientProductShots = new HashSet<EditionClientProductShots>();
            this.ProductContents = new HashSet<ProductContents>();
        }
    
        public string HTMLContent { get; set; }
        public string XMLContent { get; set; }
        public int EditionId { get; set; }
        public int ClientId { get; set; }
        public int ProductId { get; set; }
        public string URLVideo { get; set; }
    
        public virtual EditionClientProducts EditionClientProducts { get; set; }
        public virtual ICollection<EditionClientProductShots> EditionClientProductShots { get; set; }
        public virtual ICollection<ProductContents> ProductContents { get; set; }
    }
}
