//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAdverts
    {
        public ProductAdverts()
        {
            this.ClientProductAdverts = new HashSet<ClientProductAdverts>();
        }
    
        public int ProductAdvertId { get; set; }
        public string ProductAdvertName { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public string BaseURL { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<ClientProductAdverts> ClientProductAdverts { get; set; }
    }
}
