//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ClientProducts = new HashSet<ClientProducts>();
            this.DistributorProducts = new HashSet<DistributorProducts>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public bool Active { get; set; }
        public Nullable<byte> AlphabetId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
    
        public virtual Products Products1 { get; set; }
        public virtual Products Products2 { get; set; }
        public virtual Alphabet Alphabet { get; set; }
        public virtual ICollection<ClientProducts> ClientProducts { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ICollection<DistributorProducts> DistributorProducts { get; set; }
    }
}
