//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductContents
    {
        public string PlainContent { get; set; }
        public string Content { get; set; }
        public string HtmlContent { get; set; }
        public int AttributeId { get; set; }
        public int EditionId { get; set; }
        public int ClientId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Attributes Attributes { get; set; }
        public virtual ParticipantProducts ParticipantProducts { get; set; }
    }
}
