//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReassignCategories
    {
        public string NickName { get; set; }
        public System.DateTime Date { get; set; }
        public int ClientId { get; set; }
        public int ProductId { get; set; }
        public int LeafCategoryId { get; set; }
        public int CategoryThreeId { get; set; }
    
        public virtual ClientProducts ClientProducts { get; set; }
        public virtual LeafHomogeneousCategories LeafHomogeneousCategories { get; set; }
    }
}
