//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.ApplicationUsers = new HashSet<ApplicationUsers>();
        }
    
        public int RoleId { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ApplicationUsers> ApplicationUsers { get; set; }
    }
}
