//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class States
    {
        public States()
        {
            this.Addresses = new HashSet<Addresses>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
        public byte CountryId { get; set; }
        public bool Active { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual ICollection<Addresses> Addresses { get; set; }
    }
}
