//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.EditionClientProducts = new HashSet<EditionClientProducts>();
            this.ProductStatus = new HashSet<ProductStatus>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<EditionClientProducts> EditionClientProducts { get; set; }
        public virtual ICollection<ProductStatus> ProductStatus { get; set; }
    }
}
