//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.ActivitySessions = new HashSet<ActivitySessions>();
            this.ApplicationUsers = new HashSet<ApplicationUsers>();
            this.UserCountries = new HashSet<UserCountries>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string SecondLastName { get; set; }
        public string NickName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public bool Active { get; set; }
        public int CountryId { get; set; }
    
        public virtual ICollection<ActivitySessions> ActivitySessions { get; set; }
        public virtual ICollection<ApplicationUsers> ApplicationUsers { get; set; }
        public virtual CountriesUser Countries { get; set; }
        public virtual ICollection<UserCountries> UserCountries { get; set; }
    }
}
