//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCountries
    {
        public int UserId { get; set; }
        public int CountryId { get; set; }
    
        public virtual CountriesUser CountriesUser { get; set; }
        public virtual Users Users { get; set; }
    }
}
