//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guianet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works
    {
        public int WorkId { get; set; }
        public int ClientId { get; set; }
        public int ProductId { get; set; }
        public string WorkDescription { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string Module { get; set; }
        public string Details { get; set; }
        public bool Active { get; set; }
        public string WorkDescriptionLevelThree { get; set; }
    
        public virtual ClientProducts ClientProducts { get; set; }
    }
}
